### ISSUE TITLE
Batching updates

### ISSUE THREAD

**Issue by Zinggi** [elm-community/webgl#10]
This issue serves as a meta issue to help make the update process as smooth as possible, as [changes have to be approved](https://github.com/elm-community/webgl/blob/master/CONTRIBUTING.md)

---

We are currently on **1.0.1**.

### Update plan

First we could merge #4, bringing us to **1.1.0**

Next would be those two (#5, #3), bringing us to **2.0.0**.
Together with these, #11 can be implemented.

### Use cases

#4
  * Is needed to toggle different webgl features. Some games need the stencil buffer, some games don't need the depth buffer. Games that don't need a certain buffer shouldn't pay the price.
  * Ability to disable antialising (e.g. on mobile)
  * Most games probably want to disable alpha or premultiplied alpha.
  This would allow us to get rid of [these](https://github.com/zalando/elm-street-404/commit/ce7c84530c7f194c42518773f79716571f03c48e) [ugly hacks](https://github.com/Zinggi/elm-2d-game/blob/1.0.1/src/Game/TwoD/Shaders.elm#L107-L108).

#3 
  * It's nice to get a quick and dirty background sky

#5 
  * Is needed for everything that needs the stencil buffer. An example would be a mirror, a camera or object outlining.

---

If there is something to add I'll edit this first post.

**Comment by w0rm** [comment]
@Zinggi I've published 1.0.1, so you may remove the item.

**Comment by w0rm** [comment]
@Zinggi shall we include #8 too? I would say yes, because we don't want to bump the major version with each change and this pull request is ready.

**Comment by w0rm** [comment]
I think we have accumulated quite a lot of changes, so we need to get Evan's approval before merging them and releasing v2.0.0.

**Comment by Zinggi** [comment]
I've added #8. I also added #19 since we're anyway bumping the version.
And yes, I think this is enough for a nice 2.0.0 release.

**Comment by w0rm** [comment]
I have merged everything in 2.0, and will work on top of it
