### ISSUE TITLE
Only publish the necessary sources

### ISSUE THREAD

**Issue by w0rm** [elm-community/webgl#16]
Currently running `elm package install elm-community/webgl` will download all files from the repo, including examples and images, the total size is 428K. 

If we remove unneeded things, the total size will be reduced down to 80K.

As @eeue56 suggested, we can do this:

```sh
elm-package bump
git commit -a- m 'bump'
git push
git checkout <name of last commit>
rm -rf tests examples
git add .
git commit -a -m 'bump and cleanup'
git tag -a <version> -m 'init'
git push --tags
```

**Comment by fredcy** [comment]
I don't understand. What is this step about?:   `git checkout <name of last commit>`

I don't see any "tests" directory to remove. Will the "examples" folder then reside only in the gh-pages branch?

**Comment by w0rm** [comment]
@fredcy I think it means the commit hash. The idea is to keep everything in master, but only tag the  detached head where the examples and tests (which will be added in the future) are removed.
