### ISSUE TITLE
Rename Triangle to Triangles

### ISSUE THREAD

**Issue by etaque** [elm-community/webgl#19]
Hi,
I suggest to rename `Drawable(Triangle)` to `Triangles` for the following reasons:
* JS primitive name is `gl.TRIANGLES` ([reference](https://msdn.microsoft.com/en-us/library/dn302395%28v=vs.85%29.aspx))
* it's a way to draw a list of triangles, not just one

Obviously that would need to be in a major release :)

**Comment by w0rm** [comment]
@etaque thanks! I've renamed it in 2.0 branch, the api will change anyway, but the new name will be preserved.
