### ISSUE TITLE
API Outlines

### ISSUE THREAD

**Issue by evancz** [elm-community/webgl#34]
I wasn't sure how to share all the files we worked on today, but I know issues allow zip files!

So [webgl.zip](https://github.com/elm-community/webgl/files/665100/webgl.zip) contains all the files we worked on.

**Comment by w0rm** [comment]
@evancz thanks!

**Comment by w0rm** [comment]
Closing this as I have integrated the changes into the new branch. It's still work in progress though, need to complete the documentation. Will let you know when it's ready to be reviewed.
