### ISSUE TITLE
Loading images using data urls in Safari results in a CORS error

### ISSUE THREAD

**Issue by mrozbarry** [elm-community/webgl#40]
For more information and the fix, see [this issue from elm-community/canvas](https://github.com/elm-community/canvas/issues/16) and [this commit](https://github.com/elm-community/canvas/pull/20/commits/631b18d02166a064f4518042b9d5955e2f38fcf1).

This is likely more of a problem for 2d canvas than webgl, but someone is bound to run into it.

**Comment by w0rm** [comment]
@mrozbarry thanks! I've just noticed https://unsoundscapes.itch.io/mogee is not working in Safari because of this

**Comment by w0rm** [comment]
Fixed and released 2.0.2
