### ISSUE TITLE
Bump linear-algebra in examples to 3.x?

### ISSUE THREAD

**Issue by tilmans** [elm-community/webgl#57]
I was looking for Mat4 toRecord today to display the transformation input and found it in the 3.x version of linear-algebra. That's when I noticed examples are still using 2.x. Upgrading to 3.x worked so is there any reason not to upgrade the elm-packages in the example?

I can create a merge request if you want.

**Comment by w0rm** [comment]
@tilmans probably not worth doing this for the 0.18 version, as the latest stuff has been moved into the [elm-explorations](https://github.com/elm-explorations/webgl) org.
